apiVersion: v1
kind: Service
metadata:
  name: student-app-db-svc
  labels:
    app: student-app-db
spec: 
  selector:
    app: student-app-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  