apiVersion: apps/v1
kind: Deployment
metadata: 
  name: student-app-frontend
  labels: 
    app: student-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app-frontend
  template:
    metadata:
      labels:
        app: student-app-frontend
    spec: 
      containers:
        - name: student-app-container
          image: shubhamkalsait1/easy-crud-frontend:latest
          ports:  
            - containerPort: 80
          resources:  
            requests:
              cpu: 200m
              memory: 100M
            limits:
              cpu: 500m
              memory: 200M      