apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-app-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: a7b15da5a5b2f463ebe41ebdd4346fb7-2042049823.us-east-2.elb.amazonaws.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: student-app-frontend-svc
              port: 
                number: 80 
         


