apiVersion: v1
kind: Service
metadata:
  name: student-app-frontend-svc
  labels:
    app: student-app-frontend
spec: 
  selector:
    app: student-app-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
